<div class="mb-3">
    <input
        class="form-control mb-2 col <?php echo $this->getClassList() ?>  <?php echo $this->getValidation() ?>"
        type="number"
        id="filter-<?php echo $this->_data['data-index'] ?>-from"
        placeholder="From">
    <input
        class="form-control ml-4 col <?php echo $this->getClassList() ?>  <?php echo $this->getValidation() ?>"
        type="number"
        id="filter-<?php echo $this->_data['data-index'] ?>-to"
        placeholder="To">

</div>