<?php
$product  = $this->getProductData();
$images = $product->getImages();
?>


<div class="container mt-4">
    <div class="row">
        <!-- Product Image Section -->
        <div class="col-md-6">
            <div class="product-container">
                <img id="mainImage" src="<?= $this->getImageUrl($images['coverImage']) ?>" class="product-main-img" alt="<?= $product->getName() ?>">

                <div class="thumbnail-list d-flex flex-wrap mt-2">
                    <?php foreach ($images as $index => $img): ?>
                        <img src="<?= $this->getImageUrl($img) ?>" onclick="changeImage('<?= $this->getImageUrl($img) ?>', this)" class="<?= $index == 0 ? 'active' : '' ?>">

                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <!-- Product Details Section -->
        <div class="col-md-6">
            <div id="cartSuccessMessage" class="alert alert-success alert-dismissible fade show d-none" role="alert">
                
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="product-container product-info">
                <h2><?= $product->getName() ?></h2>
                <p class="product-price">Rs. <?= $product->getPrice() ?></p>
                <p><strong>SKU:</strong> <?= $product->getSku() ?></p>
                <p><strong>Available Quantity:</strong> <?= $product->getStockQuantity() ?></p>

                <form class="d-flex flex-column align-items-start gap-2">
                    <input type="hidden" name="cart[product_id]" id="product_id" value="<?php echo $product->getProductId(); ?>">

                    <div class="d-flex align-items-center gap-2">
                        <button type="button" id="decreseqnt" class="btn btn-outline-secondary btn-sm fw-bold">-</button>
                        <input type="text" id="productquantity" class="form-control text-center fw-bold" name="cart[product_quantity]"
                            value="1" readonly style="width: 50px;">
                        <button type="button" id="increseqnt" class="btn btn-outline-secondary btn-sm fw-bold">+</button>
                    </div>

                    <button type="button" id="addtocartbtn" class="btn btn-primary btn-sm">Add To Cart</button>
                </form>


                <!-- Tabs -->
                <ul class="nav nav-tabs mt-3" id="productTab">
                    <li class="nav-item">
                        <a class="nav-link active" data-tab="descriptionTab">Description</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link " data-tab="specificationsTab">Specifications</a>
                    </li>
                </ul>

                <!-- Tab Content -->
                <div class="tab-content">
                    <!-- Description -->
                    <div id="descriptionTab" class="tab-pane active">
                        <p><?= $product->getDescription() ?></p>
                    </div>

                    <!-- Specifications -->
                    <div id="specificationsTab" class="tab-pane">
                        <table class="attributes-table">
                            <?php foreach ($this->getAttributes() as $attribute): ?>
                                <?php $name = $attribute->getAttributeCode() ?>
                                <tr>
                                    <td><?php echo $attribute->getName() ?></td>
                                    <td><?php echo $product->$name ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>