<?php $customerId = $this->getCustomerId(); ?>
<?php $address = $this->getAddress(); ?>
<?php $default = $this->getDefaultAddress(); ?>


<div class="mt-5">
    <div class="card mb-4">
        <div class="card-header bg-white d-flex justify-content-between align-items-center">
            <h3 class="mb-0">Addresses</h3>
            <button id="show-ca-form-btn" class="btn btn-success">Add New Address</button>
        </div>

            <!-- Hidden Form -->
            <div id="address-form-container" class="d-none">
                <form id="checkout-form" method="POST" action="<?php echo $this->getUrl('customer/address/save') ?>" class="p-4  rounded bg-light">
                    <h4 class="fw-bold">Address</h4>
                    <div class="row g-3">
                        <input type="hidden" name="address[customer_id]" value="<?php echo $customerId ?>">
                        <input type="hidden" name="address[address_id]" value="<?php echo $address->getAddressId() ?>">
                        <div class="col-md-12">
                            <label class="fw-bold">Street Address</label>
                            <input type="text" name="address[street]" value="<?php echo $address->getStreet() ?>" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label class="fw-bold">City</label>
                            <input type="text" name="address[city]" value="<?php echo $address->getCity() ?>" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label class="fw-bold">Zip Code</label>
                            <input type="text" name="address[zip_code]" value="<?php echo $address->getZipCode() ?>" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label class="fw-bold">State</label>
                            <input type="text" name="address[state]" value="<?php echo $address->getState() ?>" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label class="fw-bold">Country</label>
                            <input type="text" name="address[country]" value="<?php echo $address->getCountry() ?>" class="form-control">
                        </div>
                    </div>
                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-primary px-5">Add Address</button>
                        <button type="button" id="hide-ca-form-btn" class="btn btn-secondary ms-2">Cancel</button>
                    </div>
                </form>
            </div>
    </div>

    <!-- Address List -->
    <div class="row">
        <!-- Default Address -->
        <div class="col-md-6 mb-3">
            <div class="card h-100">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h6 class="card-title">Default Address</h6>
                        <span class="badge bg-primary">Default</span>
                    </div>
                    <p class="card-text">
                        <?php echo $default->getStreet() ?><br>
                        <?php echo $default->getCity() . " " . $default->getZipCode() ?><br>
                        <?php echo $default->getCountry() ?><br>
                    </p>
                    <div class="d-flex gap-2 mt-3">
                       
                    </div>
                </div>
            </div>
        </div>

        <!-- Other Addresses -->
        <?php foreach ($this->getAddresses() as $address): ?>
            <div class="col-md-6 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <p class="card-text">
                            <?php echo $address->getStreet() ?><br>
                            <?php echo $address->getCity() . " " . $address->getZipCode() ?><br>
                            <?php echo $address->getCountry() ?><br>
                        </p>
                        <div class="d-flex gap-2 mt-3">
                            <a href="<?php echo $this->getUrl("*/dashboard/index") . "/?editid=" . $address->getAddressId(); ?>" class="btn btn-sm btn-outline-primary">Edit</a>
                            <button type="button" class="delete-address btn btn-sm btn-outline-danger" value="<?php echo $address->getAddressId() ?>">Delete</button>
                            <button class="make-default btn btn-sm btn-outline-secondary" value="<?php echo $address->getAddressId() ?>">Set as Default</button>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
