
<?php $orders =  $this->getOrders() ?>
<div class="card border-0 shadow-sm rounded-3 mb-4 bg-light">
    <?php if (count($orders) > 0): ?>
        <div class="card-header bg-white border-bottom d-flex justify-content-between align-items-center">
            <h3 class="mb-0 text-secondary">Recent Orders</h3>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="text-center text-secondary">Order ID</th>
                            <th class="text-secondary">Date</th>
                            <th class="text-secondary">Total</th>
                            <th class="text-secondary">Status</th>
                            <th class="text-center text-secondary">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($orders as $order): ?>
                            <tr class="table-row">
                                <td class="text-center fw-semibold"><?php echo $order->getOrderNumber() ?></td>
                                <td><?php echo date("d-m-Y", strtotime($order->getCreatedAt())) ?></td>
                                <td class="fw-bold text-dark"><?php echo $order->getTotalAmount() ?></td>
                                <td>
                                    <span class="badge rounded-pill  text-dark">
                                        <?php echo ucfirst($order->getOrderStatus()) ?>
                                    </span>
                                </td>
                                <td class="text-center">
                                    <a href="#" class="btn btn-sm btn-outline-dark px-3 rounded-pill">View</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="card-header bg-white border-bottom d-flex justify-content-between align-items-center">
            <h3 class="mb-0 ">Recent Orders</h3>
        </div>
        <div class="text-center">
            <h4 class="text-secondary">
                No Orders Found
            </h4>
        </div>
    <?php endif; ?>
</div>