<?php $data = $this->getProductData(); ?>

<div class="container p-5">
    <div id="error" class="alert alert-danger d-none"></div>
    <legend>Add New Form Data</legend>
    <form action="<?= $this->getUrl('*/*/save') ?>" id="form" method="post" enctype="multipart/form-data" class="needs-validation" novalidate>

        <input type="hidden" name="catlog_product[product_id]" value="<?php echo $data->getProductId(); ?>">

        <div class="row g-3">
            <div class="col-md-6">
                <label for="name" class="form-label">Product Name:</label>
                <input type="text" name="catlog_product[name]" id="name" value="<?php echo $data->getName(); ?>" class="form-control" required>
            </div>
            <div class="mb-3 mt-3">
                <label for="description" class="form-label">Description:</label>
                <textarea name="catlog_product[description]" id="description" class="form-control"> <?php echo $data->getDescription(); ?> </textarea>
            </div>
            <div class="col-md-6">
                <label for="sku" class="form-label">SKU:</label>
                <input type="text" name="catlog_product[sku]" id="sku" value="<?php echo $data->getSku(); ?>" class="form-control" required>
            </div>
            <div class="col-md-6">
                <label for="price" class="form-label">Price:</label>
                <input type="number" name="catlog_product[price]" id="price" value="<?php echo $data->getPrice(); ?>" class="form-control" required>
            </div>

            <div class="col-md-6">
                <label for="stock_quantity" class="form-label">Stock Quantity:</label>
                <input type="number" name="catlog_product[stock_quantity]" id="stock_quantity" value="<?php echo $data->getStockQuantity(); ?>" class="form-control" required>
            </div>
            <div class="col-md-6">
                <label for="category" class="form-label">Select Category:</label>
                <select name="catlog_product[category_id]" id="category" class="form-select" required>
                    <option value="">-- Select Category --</option>
                    <?php foreach ($this->getCategoryData() as $category): ?>
                        <option value="<?php echo $category->getCategoryId(); ?>" <?php echo (!empty($data) && $data->getCategoryId() == $category->getCategoryId()) ? 'selected' : ''; ?>>
                            <?php echo $category->getName(); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="col-md-6">
                <label for="thumbnail_image" class="form-label">Product Thumbnail:</label>
                <input type="file" class="form-control" name="catlog_product[image][thumbnail]" id="thumbnail_image">
            </div>
            <div class="col-md-6">
                <label for="images" class="form-label">Product Images:</label>
                <input type="file" class="form-control" name="catlog_product[image][]" multiple id="image">
            </div>
            <div class="row g-3 pt-5 pb-5">
            <legend for="images" class="form-label">Attributes :</legend>

                <?php foreach ($this->getAttributeData() as $attr): ?>
                    <?php echo $attrcode = $attr->getAttributeCode();?>
                
                    <div class="col-md-4 mb-3">
                        <?php echo $this->getHtmlField('label', ['for' => $attr->getName(),  'class' => 'form-label']) ?>
                        <?php echo $this->getHtmlField('input', ['type' => $attr->getType(), 'class' => 'form-control', 'name' => 'catalog_product_attribute[' . $attr->getName() . ']','value'=> $data->$attrcode]) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <a href="<?= MAGE::getBaseUrl() ?>admin/product_index/list" class="btn btn-link mt-3">Product List</a>
</div>