<style>
    .img-container {
        width: 100%;
        height: 200px;
        /* Set fixed height */
        overflow: hidden;
        /* Crop if image is too large */
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .img-container img {
        width: 100%;
        height: 100%;
        object-fit: fill;
        /* Crop image while maintaining aspect ratio */
    }

    <?php
    $products = $this->getSliderData();
    ?>
</style>
<section class="product-showcase-slider text-center">
    <h2 class="mb-4">Featured Products</h2>
    <div class="swiper myProductSwiper">
        <div class="swiper-wrapper">

            <?php foreach ($products as $product): ?>
                <div class="swiper-slide">
                    <div class="card" style="width: 18rem; ">
                        <a href="<?php echo $this->getUrl('catalog/product/view') . '/?productid=' . $product->getProductId() ?>" class="text-decoration-none text-dark">
                            <img src="<?= $this->getImageUrl($this->getImage($product->getProductId())['thumbnail']) ?>" class="card-img-top" alt="<?= $product->getName() ?>" height="340px">
                            <div class="card-body">
                                <h5 class="card-title"><?= substr($product->getName(), 0, 15) ?></h5>

                                <small>Price: Rs. <?= $product->getPrice() ?></small>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>

        </div>
        <div class="swiper-pagination"></div>
    </div>
</section>

<!-- Swiper.js & Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<script>
    var myProductSwiper = new Swiper(".myProductSwiper", {
        slidesPerView: 5,
        spaceBetween: 20,
        loop: true,
        autoplay: {
            delay: 2500,
            disableOnInteraction: false
        },
        pagination: {
            el: ".swiper-pagination",
            clickable: true
        }
    });
</script>