<head>

    <?php foreach ($this->getJs() as $js): ?>
        <script src="<?php echo Mage::getBaseUrl().'js/'.$js ?>"></script>
    <?php endforeach; ?>
    <?php foreach ($this->getCss() as $css): ?>
        <link rel="stylesheet" href="<?php echo Mage::getBaseUrl().'css/'.$css ?>">
    <?php endforeach; ?>
    <?php foreach ($this->getLink() as $link): ?>
        <link rel="stylesheet" href="<?php echo $link ?>">
    <?php endforeach; ?>
</head>