<div class="container mt-2"> 
<?php foreach ($this->getSuccess() as $key => $msg): ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> <?php echo $msg ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endforeach; ?>
<?php foreach ($this->getError() as $key => $msg): ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> <?php echo $msg ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endforeach; ?>

<?php foreach ($this->getWarning() as $key => $msg): ?>

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>warning!</strong> <?php echo $msg ?>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<?php endforeach; ?>
</div>