<!DOCTYPE html>
<html lang="en">

<?php $this->getChildHtml('head');?>

<body id="body">
    <div class="html">
        <div class="header">
            <?php $this->getChildHtml('header'); ?>
        </div>
        <div class="header">
            <?php $this->getChildHtml('message'); ?>
        </div>
        <div class="content" id="content">
            <?php $this->getChildHtml('content'); ?>
        </div>
        <div class="footer">
            <?php $this->getChildHtml('footer'); ?>
        </div>
    </div>
</body>
</html>