<?php $cartData = $this->getCart(); ?>
<?php $shippingMethods = $this->getMethods(); ?>
<?php $address = $this->getAddressData(); ?>

<div class="cart-container scc py-5">
    <!-- <div class="row">
        <div class="col-12">
            <h2 class="page-title text-center">
                <i class="fas fa-shopping-cart me-2"></i>Shopping Cart
            </h2>
        </div>
    </div> -->
    <?php if (count($this->getCartProductData()) < 1): ?>
        <div class="row">
            <div class="col-12">
                <h3 class="page-title text-center">
                    Cart is Empty Add Product First
                </h3>
            </div>
        </div>
    <?php else : ?>
        <div class="row mt-4">
            <!-- Main Cart Column -->

            <div class="col-lg-8 mb-4">
                <!-- itemmmmmssssssss goes here ------------------------------------- -->
                <?php $this->getChildHtml('cartitems') ?>
                <!-- address goes here =-------------------------------- -->
                <?php $this->getChildHtml('cartaddress') ?>

                <!-- Shipping Method Selection Form -->
                <?php $this->getChildHtml('cartshipping') ?>

                <!-- payment methods  -->
                <?php $this->getChildHtml('cartpayment') ?>

            </div>

            <!-- Order Summary Column -->
            <div class="" style="display: contents;  " id="cartsummary">
                <?php $this->getChildHtml('cartsummary') ?>
            </div>
        </div>
    <?php endif; ?>
</div>