<?php $cartData = $this->getCart(); ?>
<?php $shippingMethods = $this->getMethods(); ?>
<?php $address = $this->getAddressData(); ?>

<div class="cart-container scc py-5">
    <!-- <div class="row">
        <div class="col-12">
            <h2 class="page-title text-center">
                <i class="fas fa-shopping-cart me-2"></i>Shopping Cart
            </h2>
        </div>
    </div> -->
    <?php if (count($this->getCartProductData()) < 1): ?>
        <div class="d-flex justify-content-center align-items-center bg-light" style="height: 80vh;">
    <div class="text-center p-4 ">
        <h3 class="text-danger fw-bold mb-3">
            <i class="fas fa-shopping-cart"></i> Cart is Empty
        </h3>
        <p class="text-muted">Add products to your cart to continue shopping.</p>
        <a href="<?php echo $this->getUrl('') ?>" class="btn btn-primary mt-3">
            <i class="fas fa-arrow-left"></i> Continue Shopping
        </a>
    </div>
</div>

    <?php else : ?>
        <div class="row mt-4">
            <!-- Main Cart Column -->

            <div class="col-lg-8 mb-4">
                <!-- itemmmmmssssssss goes here ------------------------------------- -->
                <?php $this->getChildHtml('cartitems') ?>
                <!-- address goes here =-------------------------------- -->
                <?php $this->getChildHtml('cartaddress') ?>

                <!-- Shipping Method Selection Form -->
                <?php $this->getChildHtml('cartshipping') ?>

                <!-- payment methods  -->
                <?php $this->getChildHtml('cartpayment') ?>

            </div>

            <!-- Order Summary Column -->
            <div class="" style="display: contents;  " id="cartsummary">
                <?php $this->getChildHtml('cartsummary') ?>
            </div>
        </div>
    <?php endif; ?>
</div>